#DESCRIPCION DE PROYECTO
spring:
  application:
    name: Api rest de clinica con My Batis
  datasource:
    url: jdbc:mysql://localhost:3306/clinica_ws
    username: root
    password: holaCOMO

#PUERTO DE SERVIDOR
server:
  port: 8081
 
