#DESCRIPCION DE PROYECTO
spring:
  application:
    name: Api rest de clinica con My Batis
  datasource:
    url: jdbc:mysql://localhost:3306/clinica
    username: root
    password: admin
  jackson:
    serialization:
      fail-on-empty-beans: true

#PUERTO DE SERVIDOR
server:
  port: 8082


#SPRING DOC
springdoc:
  packagesToScan: com.example.controller 
  
# CONFIGURACION JWT
# ISSUER: QUIEN GENERA EL TOKEN
jwt:
  security:
    enabled: true # PARA HABILITAR O NO LA SEGURIDAD
  timezone: "America/Panama"
  issuer: "www.utp.com"
  token:
    auth:
      path: "/api/v1/jwt/auth/cliente_credential/AccessToken" #URL  que gestionara la autorizacion
    secret: "bnVsaWtlbg==" #FIRMA SECRETA DEL TOKEN
    expiresIn: 3600 #TIEMPO QUE DURA EL TOKEN
  excluded: #RUTAS QUE SERAN EXCLUIDAS
    path: ""

