#DESCRIPCION DE PROYECTO
spring:
  application:
    name: Api rest de clinica con My Batis
  datasource:
    url: jdbc:mysql://localhost:3306/clinica_ws
    username: root
    password: holaCOMO
  jackson:
    serialization:
      fail-on-empty-beans: true

#PUERTO DE SERVIDOR
server:
  port: 8081

